apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hytale-stateful.yaml
  - hytale-svc.yaml

configMapGenerator:
  - name: hytale-mods
    files:
      - mods.txt

namespace: hytale-server
